### PR TITLE
Worker api

### PR DESCRIPTION
**Pull request by wozzer72**
New worker automated integration tests, covering GET / (all), GET /:uid (single), POST and PUT actions for the first Worker screen, which includes:
* name/ID
* contract
* main job

This pull request also includes the new (real) login API, using JWT.

20190115 - Pull Request extended to include Approved Mental Health Worker and Main Job Start Date.
20190116 - Pull Request extended to include NI Number, DOB and Postcode.
20190117 - Pull Request extended to include gender and disability.

20190124 - Pull Request extended to include new reference endpoints for Ethnicity, Nationality, Country of Birth, Recruited From and Qualifications.
20190124 - Pull Request extended to include Ethnicity property.
20190126 - Pull Request extended to include Nationality, Country of Birth, RecruitedFrom, Qualification, British Citizenship, Date Arrived and Social Care Start Date properties.

### CODE REVIEW

**Comment by farynaio** [comment]
This PR has no reviewers assigned.

**Comment by wozzer72** [comment]
[Ethnicity? #152](https://trello.com/c/8XIckTL9/63-ethnicity-152)

**Comment by wozzer72** [comment]
[Nationality? #152](https://trello.com/c/eBXpK76c/64-nationality-152)

**Comment by wozzer72** [comment]
[Recruited from #152](https://trello.com/c/a01Sa1vO/68-recruited-from-152)

**Comment by wozzer72** [comment]
[Country of birth #152](https://trello.com/c/W7XnNxhH/66-country-of-birth-152)

**Comment by wozzer72** [comment]
[Highest level of Social Care qualification #152](https://trello.com/c/ACAfFG8D/81-highest-level-of-social-care-qualification-152)

**Comment by wozzer72** [comment]
Workers EPIC done from a backend point of view.

**Pull request merged**
